POST http://localhost:8081/api/cart
Content-Type: application/json

{
  "title": "Laptop",
  "quantity": 1
}

###

PATCH http://localhost:8081/api/cart/1
Content-Type: application/json

{
  "quantity": 5
}

###

DELETE http://localhost:8081/api/cart

###

//Todos
GET http://localhost:8081/todos

###
GET http://localhost:8081/todos/2

###
POST http://localhost:8081/todos
Content-Type: application/json

{
  "_id": 124,
  "task": "Clean House",
  "checked": false
}

###
POST http://localhost:8081/todos
Content-Type: application/json

{
  "stuff": ""
}

###

PATCH http://localhost:8081/todos/123
Content-Type: application/json

{
  "checked": true
}

###
PATCH http://localhost:8081/todos/123
Content-Type: application/json

{
  "checked": "true"
}
###

DELETE http://localhost:8081/todos/2